name: Deploy to Netlify
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Deploy to Netlify
        run: npx -y @netlify/mcp@latest --site-id f7f144a7-fd5d-4210-8ca9-c1d6d1821196 --proxy-path "https://netlify-mcp.netlify.app/proxy/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..oXYHMUJVXe3MRDpk.vd_A-5dLxaRdMA62Bq183ByXhjUQQgOVwj4LH6xPGKEm164PtaD4NDhTP6yyVmDiJp7_bF7UptC0b8yj02HzPOhfIkVxjJerC4lwV7ePSHIsqhngPtn2j7gIetEuuMWCBwsnrj1thsPWrtyBGhZH931EHv9Ld5B6Zn4sxj0F3zVdwsahV3DsbV37eZuYMCJy88hN2hszElnXYEul_meHEpOycmXK17aKpj7ru4DeMQsFrFQAa61XEwlQd597TQysjg3tYwTmtC-f67At5B984vb-S63l68EGx5m1Z_WMa-COMUD3UoEKc0NDyNWq-FRteCMba7D8w2_l8uyEqmFstseUZNyejg-C2kqqh9HQvjzKPw-EOP2Vpg7t_GTV0AAPTyOhFfF0.CYdCJLQGiidUUUD1PLINKg"
