name: Deploy to Netlify
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Deploy to Netlify
        run: npx -y @netlify/mcp@latest --site-id f7f144a7-fd5d-4210-8ca9-c1d6d1821196 --proxy-path "https://netlify-mcp.netlify.app/proxy/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..v4yqrQ3-0ugo3xev.5VBbxa-AyqhxodKQNse3vyBNC-179AMG392whant6iXdzaTrmY6iHcdsgs5_y4BhsXvuu2OefYVTx_mjFooLrsjQ08ELea4voui2Yu7mup-oQd1at4_jrOMy_Z4mtfviPVEo1xh2OFxjkLgPFUE4q7ckabxE144rBIWSwQhG6Byf-scknjSaGnuB34nU5LQncQzxkKkGnYGdxE2v1nU_AiBLPY8BDKT0bz6a7xZLYX5vN0imjsw8g2o_gnMD8pwbLLZ8wpjXojX1-58rYIs6CjWPwe7OAUexVwfBwOyIGy22JRgGCvGOnw_-on8hDW8x_VCSphCUx1oKSrrUbwoU8YWiLrEcGcQW-lAp28CqeUQHl1tGifM8ReYWP0SBslwx05bPWpDZ.sQyy1AJk_CLq0l9SO2V7EA"
